### ISSUE TITLE
Sending Data to an other universe than 0 does not work

### ISSUE THREAD

**Issue by khase** [gunnebo-ab/node-red-contrib-artnet#4]
i tried it using `msg.payload.universe` and changing the universe through the config.

**Comment by smadds** [comment]
Possibly a typo in line 124 of node-red-contrib-artnet.js?
`node.client.UNVERSE = [node.universe, 0];`
maybe should be
`node.client.UNIVERSE = [node.universe, 0];`

I've got no way of checking though...

**Comment by percyk** [comment]
Yes you are right there is a typo in line 124 of node-red-contrib-artnet.js

I have corrected it and tested it works fine .

I have included the updated file 

[node-red-contrib-artnet.txt](https://github.com/gunnebo-ab/node-red-contrib-artnet/files/3123722/node-red-contrib-artnet.txt)

1) Change the extension to .js  

2) Copy it to the following location : \.node-red\node_modules\node-red-contrib-artnet
